version: '3'

services:
  # Server service
  server:
    build:
      context: .
      dockerfile: dockerfile.server
    ports:
      - "8000:8000"  
    depends_on:
      - client

  # Client service
  client:
    build:
      context: .
      dockerfile: dockerfile.client
    ports:
      - "3000:3000"  
