version: '3'

services:

  #MongoDB service
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - vcl-network

  # Server service
  server:
    build:
      context: .
      dockerfile: dockerfile.server
    ports:
      - "8000:8000"  
    depends_on:
      - client
    networks:
      - vcl-network

  # Client service
  client:
    build:
      context: .
      dockerfile: dockerfile.client
    ports:
      - "3000:3000"  
    networks:
      - vcl-network

networks:
  vcl-network:
    driver: bridge

volumes:
  mongo-data: